# Site Settings
baseurl: ""
url : "https://khyun-kim.github.io"

title: 개발 블로그
author: khyun-kim
email: kh030728@gmail.com
profile:
  description: > # this means to ignore newlines until "show_excerpts:"
    안녕하세요 초보 개발자입니다.
  image: /assets/img/profile.png
show_excerpts: false # set to true to show excerpts on the homepage

social:
  github: khyun-kim
  facebook:

plugins:
 - jekyll-seo-tag
 - jekyll-paginate


#paginate
paginate: 4
paginate_path: "blog/page:num"

bootstrap:
  assets: true
